#ifndef __time_perform_h__
#define __time_perform_h__


static const int MAX_TIME_IDX = 128;
static const int TIME_START_IDX = 0;
static const int TIME_FINAL_IDX = 38;

enum {
TOTAL_EXEC_TIME				= 0,
READ_AND_INIT_TIME			= 1,
WRIT_AND_FINA_TIME			= 2,
BOUND_POINT_INST_TIME		= 3,
BOUND_POINT_INST_TIME_ACTURL= 4,
INNER_POINT_INST_TIME		= 5,
LSSP_RECV_EDGE_TIME			= 6,
NOSP_RECV_EDGE_TIME			= 7,
NOSP_RECV_FACE_TIME			= 8,
CONF_RECV_EDGE_TIME			= 9,
CONF_RECV_FACE_TIME			= 10,
CONS_RECV_EDGE_TIME			= 11,
CONS_RECV_FACE_TIME			= 12,
CONS_RECV_PNT_RMV_TIME		= 13,
QUAL_IMPRV_TIME				= 14,
TYPE_DEL_ELEM_TIME			= 15,
QUAL_RECV_SH_TRANS_TIME		= 16,
MESH_SMOOTHING_TIME			= 17,
EDGE_CONTRACT_TIME			= 18,
EDGE_SPLITTING_TIME			= 19,
QUALITY_EVAL_TIME			= 20,
FORM_INIT_CAVITY_TIME		= 21,
MODIFY_CAVITY_TIME			= 22,
UPDATE_TRIANGULATION_TIME	= 23,
CREATE_INNER_POINT_TIME		= 24,
CREATE_ELEM_PARA_TIME		= 25,
ADD_SUCC_CLEAN_TIME			= 26,
ADD_FAIL_CLEAN_TIME			= 27,
SPR_CALLING_TIME			= 28,

RECV_EDG_LOOP_TIME			= 29,
RECV_FAC_LOOP_TIME			= 30,
REMESH_ASHELL_TIME			= 31,
REMOV_AN_EDGE_TIME			= 32,
REFLEX_EDG_CH_TIME			= 33,
FIND_ALLSHELL_TIME			= 34,
DYN_RSHL_MAIN_TIME			= 35,
CHK_EDGE_RECV_TIME			= 36,
CHK_FACE_RECV_TIME			= 37,
SHELL_TRANS_TIME			= 38,
QUAL_SPR_CALLING_TIME		= 39,
};


extern double time_start[MAX_TIME_IDX];
extern double time_final[MAX_TIME_IDX];
extern double time_elaps[MAX_TIME_IDX];
extern int sphere_size_eval;

#endif /* __time_perform_h__ */
